name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Cloner le dépôt
    - uses: actions/checkout@v3

    # 2️⃣ Installer Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3️⃣ Installer les dépendances
    - name: Install dependencies
      run: npm install

    # 4️⃣ Lancer les tests
    - name: Run tests
      run: npm test

    # 5️⃣ Analyse de sécurité
    - name: Security audit
      run: npm audit --audit-level=moderate || true

    # 6️⃣ Construire l'image Docker
    - name: Build Docker image
      run: docker build -t node-api:latest .

    # 7️⃣ (Optionnel) Déployer sur Docker Hub
    - name: Push Docker image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker tag node-api:latest ${{ secrets.DOCKER_USERNAME }}/node-api:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/node-api:latest
